    <?php

    use Drupal\node\Entity\Node;

    /**
     * @file
     * Custom preprocess function for the PX Cars module.
     */ 

    /**
     * Implements hook_preprocess_node().
     * Adds custom variables to the car node template.
     */
    function px_cars_preprocess_node__car(array &$variables) {
      /** @var \Drupal\node\Entity\Node $node */
      $node = $variables['elements']['#node'];

      //get node data
      $owner_entities = $node->get('field_owner')->referencedEntities();
      if (!empty($owner_entities)) {
        $owner_name = $owner_entities[0]->get('name')->value;
      } 
      else {
        $owner_name = 'Owner not specified';
      }

      $region_entities = $node->get('field_region')->referencedEntities();
      if (!empty($region_entities)) {
        $region_name = $region_entities[0]->get('name')->value;  
      } 
      else {
        $region_name = 'Region not specified';
      }

      $variables['car_title'] = $node->getTitle(); //car title
      $variables['car_owner'] = $owner_name; //car driver
      $variables['car_region'] = $region_name; //car region6
      $teste = 'tete';
    }
    /**
     * Implements hook_theme().
     */
    function px_cars_theme() {
      return [
        'node__car' => [
          'variables' => [
            'car_title' => NULL,
            'car_owner' => NULL,
            'car_region' => NULL,
          ],
          'template' => 'node--car',
        ],
      ];
    }

/**
 * Implement hook_form_alter().
 */
function px_cars_form_alter(&$form,\Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  //check ing if the form is correct 
  if ($form_id == 'webform_submission_contact_add_form') {
    //1.Changing field order
    if (isset($form['elements']['what_vehicle_do_you_own'])) {  
      $form['elements']['what_vehicle_do_you_own']['#weight'] = rand(10, 10);
    }
    
    //2.Changing label of the Name
    if (isset($form['elements']['name'])) {
      $form['elements']['name']['#title'] = t('Please Enter Your First Name');  
    }

    //3.Add a descripition to the 'Description' fild
    if (isset($form['elements']['description'])) {
      $form['elements']['description']['#description'] = t('Please, enter some comments here!');
    }

    //4.Chenging the submit botom text.
    if (isset($form['actions']['submit'])) {
      $form['actions']['submit']['#value'] = t('Let´s go!');
    }
    
    //5.Add chekbox field 
    $form['opt_in'] = [
      '#type' => 'checkbox',
      '#title' => t('Would you like to opt in?'),
      '#default_value' => 0,
      '#description' => t('Check this box if you want to opt in.'),
    ];

  }
}